/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Max' at '15/06/16 12:27' with Gradle 2.9
 *
 * @author Max, @date 15/06/16 12:27
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
